config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :articulos
  resources :transferencias

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  root "personas#index"

  namespace :api do
    namespace :v1 do
      resources :articulos, except: [:new, :edit]
      resources :personas, except: [:new, :edit]
      resources :transferencias, except: [:new, :edit]

      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
      post 'register', to: 'users#create'
    end
  end
end

app/models/transferencia.rb
class Transferencia < ApplicationRecord
  belongs_to :articulo
  belongs_to :portador_anterior, class_name: "Persona"
  belongs_to :nuevo_portador, class_name: "Persona"

  validates :articulo, presence: true
  validates :portador_anterior, presence: true
  validates :nuevo_portador, presence: true
  validates :fecha, presence: true
  validate :portador_anterior_no_es_nuevo_portador

  private

  def portador_anterior_no_es_nuevo_portador
    if portador_anterior == nuevo_portador
      errors.add(:nuevo_portador, "no puede ser el mismo que el portador anterior")
    end
  end
end

app/controllers/api/v1/transferencias_controller.rb
module Api
  module V1
    class TransferenciasController < Api::V1::ApplicationController
      before_action :authenticate_user!, except: [:index, :show]
      before_action :set_transferencia, only: %i[ show update destroy ]

      def index
        @transferencias = Transferencia.all
        render json: @transferencias.as_json(include: [:articulo, :portador_anterior, :nuevo_portador]), status: :ok
      end

      def show
        render json: @transferencia.as_json(include: [:articulo, :portador_anterior, :nuevo_portador]), status: :ok
      rescue ActiveRecord::RecordNotFound
        render json: { error: "Transferencia not found" }, status: :not_found
      end

      def create
        @transferencia = Transferencia.new(transferencia_params)
        @articulo = Articulo.find(transferencia_params[:articulo_id])
        @transferencia.portador_anterior_id = @articulo.portador_id

        ActiveRecord::Base.transaction do
          @transferencia.save!
          @articulo.update!(portador_id: @transferencia.nuevo_portador_id)
        end

        render json: @transferencia, status: :created
      rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound => e
        render json: { errors: e.message }, status: :unprocessable_entity
      end

      def update
        if @transferencia.update(transferencia_params)
          render json: @transferencia, status: :ok
        else
          render json: { errors: @transferencia.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        @transferencia.destroy
        head :no_content
      end

      private

      def set_transferencia
        @transferencia = Transferencia.find(params[:id])
      end

      def transferencia_params
        params.require(:transferencia).permit(:articulo_id, :nuevo_portador_id, :fecha)
      end
    end
  end
end

app/controllers/transferencias_controller.rb
class TransferenciasController < ApplicationController
  allow_unauthenticated_access only: :index
  before_action :set_transferencia, only: %i[show edit update destroy]

  # GET /transferencias
  def index
    @transferencias = Transferencia.all
  end

  # GET /transferencias/1
  def show
  end

  # GET /transferencias/new
  def new
    @transferencia = Transferencia.new
  end

  # GET /transferencias/1/edit
  def edit
  end

  # POST /transferencias
  def create
    @transferencia = Transferencia.new(transferencia_params)
    @articulo = Articulo.find(transferencia_params[:articulo_id])
    @transferencia.portador_anterior_id = @articulo.portador_id

    if @transferencia.save
      @articulo.update(portador_id: @transferencia.nuevo_portador_id)
      redirect_to @transferencia, notice: "Transferencia was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /transferencias/1
  def update
    if @transferencia.update(transferencia_params)
      redirect_to transferencia_path(@transferencia), notice: "Transferencia actualizada correctamente."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /transferencias/1
  def destroy
    @transferencia.destroy
    redirect_to transferencias_path, notice: "Transferencia eliminada correctamente."
  end

  private

  def set_transferencia
    @transferencia = Transferencia.find(params[:id])
  end

  def transferencia_params
    params.require(:transferencia).permit(:articulo_id, :nuevo_portador_id, :fecha)
  end
end

app/helpers/transferencia_helper.rb
module TransferenciaHelper
end

app/helpers/transferencias_helper.rb
module TransferenciasHelper
end

app/views/transferencias/_form.html.erb
<%= form_with(model: transferencia, local: true) do |form| %>
  <% if transferencia.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transferencia.errors.count, "error") %> impidió guardar la transferencia:</h2>
      <ul>
        <% transferencia.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :articulo_id, "Artículo", style: "display: block" %>
    <%= form.collection_select :articulo_id, Articulo.all, :id, ->(a){ "#{a.marca} #{a.modelo}" }, prompt: "Seleccione un artículo" %>
  </div>

  <div>
    <%= form.label :portador_anterior_id, "Portador Anterior", style: "display: block" %>
    <%= form.collection_select :portador_anterior_id, Persona.all, :id, ->(p){ "#{p.nombre} #{p.apellido}" }, prompt: "Seleccione una persona" %>
  </div>

  <div>
    <%= form.label :nuevo_portador_id, "Nuevo Portador", style: "display: block" %>
    <%= form.collection_select :nuevo_portador_id, Persona.all, :id, ->(p){ "#{p.nombre} #{p.apellido}" }, prompt: "Seleccione una persona" %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transferencias/_transferencia.html.erb
<div id="<%= dom_id transferencia %>">
  <p>
    <strong>Artículo:</strong>
    <%= transferencia.articulo.marca %> <%= transferencia.articulo.modelo %>
  </p>

  <p>
    <strong>Portador Anterior:</strong>
    <%= link_to "#{transferencia.portador_anterior.nombre} #{transferencia.portador_anterior.apellido}", persona_path(transferencia.portador_anterior) %>
  </p>

  <p>
    <strong>Nuevo Portador:</strong>
    <%= link_to "#{transferencia.nuevo_portador.nombre} #{transferencia.nuevo_portador.apellido}", persona_path(transferencia.nuevo_portador) %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= transferencia.fecha %>
  </p>

  <p>
    <%= link_to "Mostrar", transferencia %> |
    <%= link_to "Editar", edit_transferencia_path(transferencia) %> |
    <%= button_to "Eliminar", transferencia, method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } } %>
  </p>
  <hr>
</div>

app/views/transferencias/edit.html.erb
<h1>Editar Transferencia</h1>

<%= render "form", transferencia: @transferencia %>

<%= link_to "Mostrar", transferencia_path(@transferencia) %> |
<%= link_to "Volver al listado", transferencias_path %>

app/views/transferencias/index.html.erb
<h1>Listado de Transferencias</h1>

<%= link_to "Nueva Transferencia", new_transferencia_path %>

<div id="transferencias">
  <%= render @transferencias %>
</div>

<div>
  <%= link_to "Nueva Transferencia", new_transferencia_path %>
</div>

app/views/transferencias/new.html.erb
<h1>Nueva Transferencia</h1>

<%= render "form", transferencia: @transferencia %>

<%= link_to "Volver al listado", transferencias_path %>

app/views/transferencias/show.html.erb
<h1>Transferencia</h1>

<p>
  Artículo: <%= @transferencia.articulo.marca %> <%= @transferencia.articulo.modelo %><br>
  Portador Anterior: <%= @transferencia.portador_anterior.nombre %> <%= @transferencia.portador_anterior.apellido %><br>
  Nuevo Portador: <%= @transferencia.nuevo_portador.nombre %> <%= @transferencia.nuevo_portador.apellido %><br>
  Fecha: <%= @transferencia.fecha %>
</p>

<%= link_to "Editar", edit_transferencia_path(@transferencia) %> |
<%= link_to "Volver al listado", transferencias_path %>