config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :articulos
  resources :transferencias

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  root "personas#index"

  namespace :api do
    namespace :v1 do
      resources :articulos, except: [:new, :edit]
      resources :personas, except: [:new, :edit]
      resources :transferencias, except: [:new, :edit]

      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
      post 'register', to: 'users#create'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Personas", personas_path %> |
      <%= link_to "Articulos", articulos_path %> |
      <%= link_to "Transferencias", transferencias_path %>
      <% if authenticated? %>
        | <%= button_to "Logout", logout_path, method: :delete, data: { turbo: false } %>
      <% else %>
        | <%= link_to "Login", login_path %> |
        <%= link_to "Register", register_path %>
      <% end %>
    </nav>
    <hr>
    <%= yield %>
  </body>
</html>